### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by dresc** [fixme-lausanne/mpd-wsgi#50]
12:13:09 pi@Ayaka:~/radio/mpdwsgi-web$ npm run build

> mpdwsgi-client-web@2.0.0-alpha build /home/pi/radio/mpdwsgi-web
> npm run build:js && npm run build:css
> 
> mpdwsgi-client-web@2.0.0-alpha prebuild:js /home/pi/radio/mpdwsgi-web
> mkdir -p static/output
> 
> mpdwsgi-client-web@2.0.0-alpha build:js /home/pi/radio/mpdwsgi-web
> browserify -e src/index.jsx -o static/output/bundle.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/radio/mpdwsgi-web/node_modules/babelify/index.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! mpdwsgi-client-web@2.0.0-alpha build:js: `browserify -e src/index.jsx -o static/output/bundle.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the mpdwsgi-client-web@2.0.0-alpha build:js script.
npm ERR! This is most likely a problem with the mpdwsgi-client-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -e src/index.jsx -o static/output/bundle.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls mpdwsgi-client-web
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.21-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:js"
npm ERR! cwd /home/pi/radio/mpdwsgi-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/radio/mpdwsgi-web/npm-debug.log
npm ERR! not ok code 0

npm ERR! mpdwsgi-client-web@2.0.0-alpha build: `npm run build:js && npm run build:css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mpdwsgi-client-web@2.0.0-alpha build script.
npm ERR! This is most likely a problem with the mpdwsgi-client-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:js && npm run build:css
npm ERR! You can get their info via:
npm ERR!     npm owner ls mpdwsgi-client-web
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.21-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/pi/radio/mpdwsgi-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/radio/mpdwsgi-web/npm-debug.log
npm ERR! not ok code 0

**Comment by dgellow** [comment]
Hello @dresc,
Tu peux me dire exactement les commandes que tu as run?

**Comment by dgellow** [comment]
@dresc Ah, d'ailleurs c'est pas sur le bon projet, ton problème est avec https://github.com/fixme-lausanne/mpdwsgi-web
